#ifndef _SIFIVE_EVENTS_H
#define _SIFIVE_EVENTS_H

typedef char* sifive_u74_event_name;

static const sifive_u74_event_name event_list[] = {
    "EXCEPTION_TAKEN",
    "INTEGER_LOAD_RETIRED",
    "INTEGER_STORE_RETIRED",
    "ATOMIC_MEMORY_RETIRED",
    "SYSTEM_INSTRUCTION_RETIRED",
    "INTEGER_ARITHMETIC_RETIRED",
    "CONDITIONAL_BRANCH_RETIRED",
    "JAL_INSTRUCTION_RETIRED",
    "JALR_INSTRUCTION_RETIRED",
    "INTEGER_MULTIPLICATION_RETIRED",
    "INTEGER_DIVISION_RETIRED",
    "FP_LOAD_RETIRED",
    "FP_STORE_RETIRED",
    "FP_ADDITION_RETIRED",
    "FP_MULTIPLICATION_RETIRED",
    "FP_FUSEDMADD_RETIRED",
    "FP_DIV_SQRT_RETIRED",
    "OTHER_FP_RETIRED",
    "ADDRESSGEN_INTERLOCK",
    "LONGLAT_INTERLOCK",
    "CSR_READ_INTERLOCK",
    "ICACHE_ITIM_BUSY",
    "DCACHE_DTIM_BUSY",
    "BRANCH_DIRECTION_MISPREDICTION",
    "BRANCH_TARGET_MISPREDICTION",
    "PIPE_FLUSH_CSR_WRITE",
    "PIPE_FLUSH_OTHER_EVENT",
    "INTEGER_MULTIPLICATION_INTERLOCK",
    "FP_INTERLOCK",
    "ICACHE_RETIRED",
    "DCACHE_MISS_MMIO_ACCESSES",
    "DCACHE_WRITEBACK",
    "INST_TLB_MISS",
    "DATA_TLB_MISS",
    "UTLB_MISS",
};

#endif
