/*
 * =============================================================================
 *
 *                   Copyright (c) 2025 BSC
 *                             All rights reserved
 *
 * This file contains BSC proprietary and confidential information and has
 * been developed by BSC within the EPI-SGA1 Project (GA 826647).
 * The permission rights for this file are governed by the EPI Grant Agreement
 * and the EPI Consortium Agreement.
 *
 * ===============================[ INFORMATION ]===============================
 *
 * Author(s)  : Rafel Bros Esqueu
                Fabio Banchelli
 * Contact(s) : rafel.brosesqueu@bsc.es
                fabio.banchelli@bsc.es
 */

/*
 * EUPILOT VEC Atrevido+VPU RISC-V Core
 */

static const riscv_entry_t riscv_eupilot_vec_atrevido_pe[] = {
    //Atrevido
    {.name = "L1_ICM",
     .code = 0x001,
     .desc = "Level 1 instruction cache misses" },
    {.name = "L1_DCM",
     .code = 0x002,
     .desc = "Level 1 data cache misses" },
    {.name = "TLB_IM",
     .code = 0x003,
     .desc = "Instruction translation lookaside buffer misses" },
    {.name = "TLB_DM",
     .code = 0x004,
     .desc = "Data translation lookaside buffer misses" },
    {.name = "NUM_EXCEPTIONS",
     .code = 0x005,
     .desc = "Number of Exceptions" },
    {.name = "NUM_RET_TRAP_INST",
     .code = 0x006,
     .desc = "Number of executed ERET/MRET/SRET instructions" },
    {.name = "NUM_NUKES",
     .code = 0x007,
     .desc = "Number of nukes" },
    {.name = "NUM_MISFETCHES",
     .code = 0x008,
     .desc = "Misfetches" },
    {.name = "NUM_MISPREDICTS",
     .code = 0x009,
     .desc = "Mispredicts" },
    {.name = "NUM_LOAD_LIKE_INST",
     .code = 0x00A,
     .desc = "Number of Load-like committed instructions" },
    {.name = "NUM_STORE_LIKE_INST",
     .code = 0x00B,
     .desc = "Number of Store-like committed instructions" },
    {.name = "NUM_CTRL_FLOW_INST",
     .code = 0x00C,
     .desc = "Number of Control Flow committed instructions" },

    //VPU Counters
    {.name = "VPU_COMPLETED_INST",
     .code = 0x020,
     .desc = "Number of finished intructions at the VPU" },
    {.name = "VPU_ISSUED_INST",
     .code = 0x040,
     .desc = "Number of issued instructions at the VPU" },
    {.name = "VPU_KILLS_COUNT",
     .code = 0x060,
     .desc = "Number of kill events (not instructions) at the VPU" },
    {.name = "VPU_LOAD_RETRIES",
     .code = 0x080,
     .desc = "Number of load instructions with retries" },
    {.name = "VPU_OVERLAPS_TAKEN",
     .code = 0x0A0,
     .desc = "Number of instructions taking advantage of overlapping" },
    {.name = "VPU_MEM_DEPEN",
     .code = 0x0C0,
     .desc = "Number of memory instructions with dependencies (index or mask)" },
    {.name = "VPU_ACTIVE",
     .code = 0x0E0,
     .desc = "Number of cycles the VPU has been active" },
    {.name = "VPU_STALLED",
     .code = 0x100,
     .desc ="Number of cycles the VPU has been stalled" },
    {.name = "VPU_RENAMING_STALL",
     .code = 0x120,
     .desc = "Number of cycles stalled at renaming due to lack of physical registers" },
    {.name = "VPU_MASKED_STALL",
     .code = 0x140,
     .desc = "Number of cycles stalled at the renaming due to the lack of physical registers for mask" },
    {.name = "VPU_PRE_ISSUE_STALL",
     .code = 0x160,
     .desc = "Number of cycles stalled at the Pre-Issue Queue" },
    {.name = "VPU_UNPACKER_STALL",
     .code = 0x180,
     .desc = "Number of cycles stalled at the Unpacker" },
    {.name = "VPU_ROB_STALL",
     .code = 0x1A0,
     .desc = "Number of cycles stalled at the Reorder Buffer" },
    {.name = "VPU_ARITH_Q_STALL",
     .code = 0x1C0,
     .desc = "Number of cycles stalled because the Arithmetic Queue is full" },
    {.name = "VPU_MEMORY_Q_STALL",
     .code = 0x1E0,
     .desc = "Number of cycles stalled because the Memory Queue is full" },
    {.name = "VPU_PRE_ISSUE_EMPTY",
     .code = 0x200,
     .desc = "Number of cycles the Pre-Issue Queue has been empty" },
    {.name = "VPU_UNPACKER_EMPTY",
     .code = 0x220,
     .desc = "Number of cycles the Unpacker has been empty" },
    {.name = "VPU_ROB_EMPTY",
     .code = 0x240,
     .desc = "Number of cycles the Reorder Buffer has been empty" },
    {.name = "VPU_ARITH_Q_EMPTY",
     .code = 0x260,
     .desc = "Number of cycles the Arithmetic Queue has been empty" },
    {.name = "VPU_MEMORY_Q_EMPTY",
     .code = 0x280,
     .desc = "Number of cycles the Memory Queue has been empty" },
    {.name = "VPU_ARITH_INST",
     .code = 0x2A0,
     .desc = "Number of arithmetic instructions issued" },
    {.name = "VPU_MEM_INST",
     .code = 0x2C0,
     .desc = "Number of memory instructions issued" },
    {.name = "VPU_OVERLAP_INST",
     .code = 0x2E0,
     .desc = "Number of overlappable instructions issued" },
    {.name = "VPU_FP_INST",
     .code = 0x300,
     .desc = "Number of Floating-Point instructions issued" },
    {.name = "VPU_FP_FMA_INST",
     .code = 0x320,
     .desc = "Number of Floating-Point FMA instructions issued" },
    {.name = "FP_WID_FMA_INST",
     .code = 0x340,
     .desc = "Number of Floating-Point Widening FMA instructions issued" },
    {.name = "FP_NOT_FMA_INST",
     .code = 0x360,
     .desc = "Number of Floating-Point not FMA instructions issued" },
    {.name = "FP_WIDEN_INST",
     .code = 0x380,
     .desc = "Number of Floating-Point Widening instructions issued" },
    {.name = "FP_REDUC_INST",
     .code = 0x3A0,
     .desc = "Number of Floating-Point Reduction instructions issued" },
    {.name = "WIDENING_INST",
     .code = 0x3C0,
     .desc = "Number of Widening instructions issued" },
    {.name = "NARROWING_INST",
     .code = 0x3E0,
     .desc = "Number of Narrowing instructions issued" },
    {.name = "INT_FMA_INST",
     .code = 0x400,
     .desc = "Number of Integer FMA instructions issued" },
    {.name = "INT_REDUC_INST",
     .code = 0x420,
     .desc = "Number of Integer Reduction instructions issued" },
    {.name = "INT_NO_REDUC_INST",
     .code = 0x440,
     .desc = "Number of Intefer no Reduction instructions issued" },
    {.name = "GATHER_INST",
     .code = 0x460,
     .desc = "Number of Gather instructions issued" },
    {.name = "SLIDE_INST",
     .code = 0x480,
     .desc = "Number of Slide instructions issued" },
    {.name = "VMV_INST",
     .code = 0x4A0,
     .desc = "Number of Vector Move instructions (vmv) issued" },
    {.name = "ONE_OPER_INST",
     .code = 0x4C0,
     .desc = "Number of instructions with one operand issued" },
    {.name = "TWO_OPER_INST",
     .code = 0x4E0,
     .desc = "Number of instructions with two operands issued" },
    {.name = "THREE_OPER_INST",
     .code = 0x500,
     .desc = "Number of instructions with three operands issued" },
    {.name = "SCALAR_OPER_INST",
     .code = 0x520,
     .desc = "Number of instructions with scalar operand issued" },
    {.name = "MEM_MASKED_INST",
     .code = 0x540,
     .desc = "Number of Memory Masked instructions issued" },
    {.name = "MEM_INDEXED_INST",
     .code = 0x560,
     .desc = "Number of Memory Indexed instructions issued" },
    {.name = "FAST_VMV_INST",
     .code = 0x580,
     .desc = "Number of Fast VMV instructions done" },
    {.name = "LANE_ANY_FREE",
     .code = 0x5A0,
     .desc = "Number of cycles Any VPU Lane is Free" },
    {.name = "LANE_0_FREE",
     .code = 0x5C0,
     .desc = "Number of cycles VPU Lane 0 is Free" },
    {.name = "LANE_1_FREE",
     .code = 0x5E0,
     .desc = "Number of cycles VPU Lane 1 is Free" },
    {.name = "LANE_2_FREE",
     .code = 0x600,
     .desc = "Number of cycles VPU Lane 2 is Free" },
    {.name = "LANE_3_FREE",
     .code = 0x620,
     .desc = "Number of cycles VPU Lane 3 is Free" },
    {.name = "LANE_4_FREE",
     .code = 0x640,
     .desc = "Number of cycles VPU Lane 4 is Free" },
    {.name = "LANE_5_FREE",
     .code = 0x660,
     .desc = "Number of cycles VPU Lane 5 is Free" },
    {.name = "LANE_6_FREE",
     .code = 0x680,
     .desc = "Number of cycles VPU Lane 6 is Free" },
    {.name = "LANE_7_FREE",
     .code = 0x6A0,
     .desc = "Number of cycles VPU Lane 7 is Free" },
    {.name = "LOAD_INSTR",
     .code = 0x6C0,
     .desc = "Number of memory load instructions issued" },
    {.name = "STORE_INSTR",
     .code = 0x6E0,
     .desc = "Number of memory store instructions issued" },
    {.name = "LOAD_VALID_CYCLES",
     .code = 0x700,
     .desc = "Valid is set on a vector load" },
    {.name = "STORE_VALID_CYCLES",
     .code = 0x720,
     .desc = "Valid is set on a vector store" }
};
